import logging
import time

from providers import (
    ProviderRegistry,
    LocalProvider,
    ComfyUIProvider,
    HuggingFaceProvider,
    BrowserFallbackProvider,
    IdentityProvider,
)

logger = logging.getLogger(__name__)

# Global singleton
_registry: ProviderRegistry | None = None


def get_registry() -> ProviderRegistry:
    global _registry
    if _registry is None:
        _registry = ProviderRegistry()
        _registry.register(IdentityProvider())
        _registry.register(ComfyUIProvider())
        _registry.register(LocalProvider())
        _registry.register(HuggingFaceProvider())
        _registry.register(BrowserFallbackProvider())

        logger.info("=== Avatar Provider Detection ===")
        available = _registry.detect_all()
        if available:
            best = _registry.select_best()
            logger.info(f"Available providers: {available}")
            logger.info(f"Selected: {best}")
        else:
            logger.info("No backend providers available — will use BrowserFallbackProvider")
            _registry.active = "browser_fallback"
        logger.info("=================================")
    return _registry


def generate_avatar(image_bytes: bytes, prompt: str = "") -> dict:
    registry = get_registry()
    active_before = registry.get_active_name()
    start = time.time()

    success, result, provider_name = registry.generate_with_fallback(image_bytes, prompt)

    elapsed = time.time() - start

    if success and isinstance(result, bytes):
        import base64
        import io
        from PIL import Image

        try:
            img = Image.open(io.BytesIO(result))
            width, height = img.size
        except Exception:
            width, height = 0, 0

        b64 = base64.b64encode(result).decode()
        data_url = f"data:image/png;base64,{b64}"

        logger.info(
            f"Avatar generated by {provider_name} "
            f"({elapsed:.1f}s, {len(result)/1024:.0f}KB, {width}x{height})"
        )

        return {
            "success": True,
            "avatar": data_url,
            "model_used": provider_name,
            "inference_time_s": round(elapsed, 1),
        }

    if result == "__USE_BROWSER_FALLBACK__":
        return {
            "success": False,
            "use_browser_fallback": True,
            "error": "No backend AI provider available — use browser-based processing",
            "model_used": "browser_fallback",
        }

    return {
        "success": False,
        "error": str(result)[:300],
        "model_used": provider_name,
    }


def get_diagnostics() -> dict:
    registry = get_registry()
    providers = registry.get_all_status()
    return {
        "active_provider": registry.get_active_name(),
        "providers": providers,
        "total_providers": len(providers),
        "available_count": sum(1 for p in providers if p["available"]),
    }
